version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DJANGO_ENV=local
      - DEBUG=1
    command: python manage.py runserver 0.0.0.0:8000
