# Generated by Django 5.1.3 on 2024-11-07 17:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_file_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='share_link',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='file',
            name='shared',
            field=models.BooleanField(default=False),
        ),
    ]
